name : 'headers-check' 
description: 'GitHub Action to check for security of HTTP headers' 

inputs: 
 url:
   description: 'URL of headers to be scanned'
   required: true
 GITHUB_TOKEN:
   description: 'GitHub token'
   required: true

outputs: 
 header-issues: 
  description : 'All headers that may have issues'

runs:  
  using: 'node16'
  main: 'dist/index.js'
