name: security-headers-check
on:
  pull_request:
    types: [opened]

jobs: 
 security-headers-check:
 
  runs-on : ubuntu-latest
  
  name : Check headers for violations of security best practises
  
  steps:
    - name : Security headers check
      id : headerscheck
      uses: AudreyBudryte2/security-headers@v2
      with:
       url: 'http://google.com'
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment results of security headers check
      uses: mb2dev/github-action-comment-pull-request@1.0.0
      with:
        message: "${{steps.headerscheck.outputs.header-issues}}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
